### ISSUE TITLE
Breaking the 200 posts max

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/snitch#25]
(At least) with the current Snitch Version and WP 4.9.6 the maximum of 200 kept posts in the database does not seem to work.
In the support forums [we have someone](https://wordpress.org/support/topic/big-snitch-log/) claiming to have close to 1500 snitch posts in her DB, in my test install there are at least 220 posts.

**Comment by staude** [comment]
The phrase "no more than 200" is unfortunate.
By default, Snitch keeps the 200 most recent entries when deleting.
The deletion is done by cron once a day, so that in normal operation there are more than 200 in the list.
The number 200 can be changed by filterhook 'snitch_cleanup_items'.

In my own installation I also had 1700 entries.
However, a manual execution of the event then deleted correctly.
I deactivated and reactivated my snitch once and check if it has deleted correctly tomorrow via cron or not.

**Comment by staude** [comment]
In my installation I currently have 476 entries. The oldest are 3 hours old. That means that the daily cleanup this afternoon is over. 
That is perfectly correct.

It is therefore only possible that the event no longer exists in the system cron. It helps to deactivate the plugin and reactivate it.

so I close the ticket

**Comment by Zodiac1978** [comment]
Re-opening this issue as a reminder until documentation is fixed.

**Comment by alexlii1971** [comment]
I test it on multisite, same question here.

any progress please?

**Comment by tbnv** [comment]
Bug still present in WP 5.2+

**Comment by staude** [comment]
Is the point Documentation still open with publish of  https://snitch.pluginkollektiv.org/de/dokumentation/

**Comment by krafit** [comment]
I updated the documentation accordingly in the [German](https://snitch.pluginkollektiv.org/de/dokumentation/#clenaup) and [English](https://snitch.pluginkollektiv.org/documentation/#clenaup) version.
