### ISSUE TITLE
Potential illegal string offset in snitch_cpt.class.php

### ISSUE THREAD

**Issue by glueckpress** [pluginkollektiv/snitch#4]
> I just installed the plugin, and it's already giving me thousands (over 3K in five mins already) for the same reason (illegal string offset in [snitch_cpt.class.php on lines 565 and 566](https://github.com/pluginkollektiv/snitch/blob/master/inc/snitch_cpt.class.php#L565-L566)).
> 
> —https://wordpress.org/support/topic/bogging-down-with-thousands-of-alerts-for-the-same-lines

**Comment by swissspidy** [comment]
This error occurs because no `_snitch_meta` meta value exists for a post. In this case we could either return early if `! isset` and not print anything, or pass a default value for `$meta['type']` and `$meta['name']`.

However, I wonder why this data isn't set (looks like that happens in [`snitch_http.class.php`](https://github.com/pluginkollektiv/snitch/blob/7a00702205d739fe9c4017828ac257d50dd34756/inc/snitch_http.class.php#L122)).

**Comment by glueckpress** [comment]
> In this case we could either return early `if ! isset` and not print anything, or pass a default value for `$meta['type']` and `$meta['name']`.

@swissspidy My gut understanding would be the first (bail early). Do you see any advantages of setting default values?

**Comment by swissspidy** [comment]
@glueckpress The problem with bailing early is that log file would be incomplete. There are usually default values in place (_WordPress_ and _Core_) when saving, so no idea why a post got saved without that.

IMHO we should use the same default values for the output. I can fix that soon-ish.

**Comment by glueckpress** [comment]
@swissspidy :+1:

**Comment by swissspidy** [comment]
Currently learning for exams, so won't have time until end of month.
